### ISSUE TITLE
Spotify icon, remove icons misaligned when player is certain widths

### ISSUE THREAD

**Issue by pdaddyo** [pdaddyo/soundbounce#109]
http://ss.westie.sh/SrPD

**Comment by mreinhardt** [comment]
Has this been fixed? I tried reproducing by resizing from super wide to super narrow but wasn't able to.

**Comment by andrewthecoder** [comment]
Hmm, actually yeah I believe it was fixed a couple of months ago along with a bunch of other things, it was just a line of CSS.
