### ISSUE TITLE
Facebook/Twitter/Github links on the login screen as their respective logos

### ISSUE THREAD

**Issue by noafro1991** [pdaddyo/soundbounce#127]
For extra linkage!

**Comment by JohnnyCrazy** [comment]
How about this simple approach? 
![image](http://i.imgur.com/J6ylboL.png)

Although I'm not sure if it's a good idea opening the webpage in soundbounce, since a lot of users maybe want it in there default browser.

**Comment by pdaddyo** [comment]
We can call the external (default) browser like so:

spotifyBrowserApi.openUrl('http://twitter.com/_Soundbounce_');
