### ISSUE TITLE
Remove the "track not playable" message when the song has finished playing

### ISSUE THREAD

**Issue by Delthas** [pdaddyo/soundbounce#128]
As I usually leave my client minimized for hours, when I open it back again, I don't want to have to close the "track not playable" popup if the not-playable song error happened 3 hours ago.
ie please automatically close the "track not available" popup as soon as the bugged tracked stops playing.

**Comment by pdaddyo** [comment]
closing because this will be fixed in #145 (not yet fixed though!)
