### ISSUE TITLE
Work Skin

### ISSUE THREAD

**Issue by zackram** [pdaddyo/soundbounce#140]
It would be awesome if there was some type of bare-bones skin option for people at work. Text only, dark color scheme (black/grey), all small font sizes, and the ability to toggle the chat on/off would be DOPE. 

:)

**Comment by Tonybyte** [comment]
I am making a version of this for myself soon so I'll get it to you. :) Even at the smallest size, the art doesn't take up much room. It might give more vertical listings, I'll experiment. Did you want to hide the covers for more room or to be more stealth?

**Comment by pdaddyo** [comment]
Great idea - however I'm closing this issue here since we won't merge themes into the main project, they'll always be separate.  Cheers!
