### ISSUE TITLE
Multiple room admins front-end UI

### ISSUE THREAD

**Issue by EdPoole1** [pdaddyo/soundbounce#141]
Would it be possible -- and (hopefully) relatively simple -- to allow more than one user exercise room administrator privileges?  Specifically, the ability to deletes songs added the playlist be OTHER users, change room name.

Thanks - love what's right so far, would love even more if we could go back to our multi-admin way of doing business.

**Comment by JohnnyCrazy** [comment]
Yes, looking at the room-system, it's already possible, but needs to be implemented on the front-end. (Make someone admin, remove admin privileges)

**Comment by EdPoole1** [comment]
Are you saying I should already be able to do it?  Mind you, my technical skills are just shy of your average house cat, so I'd need someone to point me at a button or dialog box. 

Ed

**Comment by zackram** [comment]
To clarify, I believe Johnny is saying that this would be easy to implement on the "front end" (end user experience) but is only currently possible on the "back-end" (developer world). I would expect that you'll see this functionality soon. :)

**Comment by JohnnyCrazy** [comment]
Yes, thanks @zackram :)

Currently all room-admins are stored in a JSON-array like this:
````json
"admins": [
    "someID"
]
````
So there is no problem adding more admins to it, we just need to built it into the user's view (e.g display a button like 'make room-admin') and implement it on the server-side

**Comment by pdaddyo** [comment]
Yep you're all correct - this is supported by the server backend, and will be coming to the frontend along with the overhaul of the current listeners in room UI.

**Comment by pdaddyo** [comment]
FYI, this will be fixed once #143 is closed.  No ETA yet.

**Comment by pdaddyo** [comment]
This is now available! 

Not through new UI, but using the new server commands feature.  If you're a room admin, type

/commands    for a list of commands

/addadmin to add an admin
/removeadmin to remove admin

New admins will have to re-connect to the room in order to be able to make changes.

**Comment by bgod** [comment]
Good news!  So what's the argument for /addadmin?  Spotify uid?  Soundbounce (Spotify|FB) login id?

**Comment by pdaddyo** [comment]
If you type /addadmin it gives you help text too.  Cheers! Closing this now.

**Comment by EdPoole1** [comment]
Thanks so much, Paul!  On behalf of Wizard Rock, let me say this: you rock!  So happy to have a new home for our room. 

Have a great weekend

Ed

**Comment by bgod** [comment]
At some point, a /listadmin would be helpful too!  :smile:  Thanks again!

**Comment by pdaddyo** [comment]
Good idea @bgod, added as issue #178
