### ISSUE TITLE
Voting from the chat window sometimes gives votes or adds the wrong song.

### ISSUE THREAD

**Issue by bgod** [pdaddyo/soundbounce#142]
Happened to me twice today.  In the most recent case I clicked on a song in chat and it voted for a different song, then I deleted the song that incorrectly got the vote, tried to vote for the initial song again, and it added the wrong song back to the playlist.

I voted for the intended song from the track list window and it worked fine.

**Comment by pdaddyo** [comment]
I've never seen this, and looking at the code it's very surprising this could have happened.  Is there any chance the chat window scrolled up as you were clicking?   I presume not since you're a "veteran" soundbounce user :)  If you can name the tracks this happened with I'll do some testing here.

**Comment by bgod** [comment]
The first time it happened I chalked it up to a possible mis-click.  But the 2nd occurrence was repeatable.  The song I was trying to vote for was Glory by Wye Oak.  I don't recall the name of the song that was getting the votes instead.  Will keep an eye on it.  I wonder if it could have something to do with deleting tracks.  Could that mess with indexing of some sort?

**Comment by pdaddyo** [comment]
This just happened to me! I know what's causing the re-adds (it's allowing voting from chat window on songs that have played).  Will fix!

**Comment by bgod** [comment]
Ah, good news!

**Comment by Allikin** [comment]
Happened to me now too. I voted (in chat) for a track that was removed from the room, and another track got the vote.

![image](https://cloud.githubusercontent.com/assets/5058114/5630611/bf4cef6e-95bf-11e4-8b77-9245abfa8b67.png)
