### ISSUE TITLE
Update UI for Listener list in room

### ISSUE THREAD

**Issue by MYPETFISH** [pdaddyo/soundbounce#143]
section of UI should list users in room
- disploay includes user count
- optional functionality to open user profile in Spotify
- optional hide 
- display does not use excessive space
display could be rolling ticker of user ids, a list with/out profile pictures

**Comment by danwl** [comment]
I'm in your opinion. A small list with small pictures ... is better than the actual list.

**Comment by pdaddyo** [comment]
Thanks for feedback guys.  User list will be getting an overhaul with
clickable links to spotify profiles as described.  No ETA yet though!

**Comment by JohnnyCrazy** [comment]
I'm on this, PR should be out in 1-3 days

**Comment by pdaddyo** [comment]
Thanks!
