### ISSUE TITLE
Track unavailable message should be a temporary "popover", and should close automatically.

### ISSUE THREAD

**Issue by noafro1991** [pdaddyo/soundbounce#145]
If you preview a track while you can't listen to the main song playing, this message appears every time you stop previewing - then you have to click it to get rid of it.

I reckon you could solve this issue by providing a "button click" area that's the size of the Soundbounce window for clicking the usual "X", or you could set it so that the message disappears when you move your mouse inside the window.

**Comment by pdaddyo** [comment]
Yes this definitely needs improving, should be a "popover" error message that only appears whilst song is playing.  Will fix!

**Comment by pdaddyo** [comment]
I've just realised instead of my suggested popover, it should post in the chat from Soundbounce, like server commands.  It's out the way, but you have a history there later when you come back so you know what was missing.
