### ISSUE TITLE
Scrolling / using the UI is laggy

### ISSUE THREAD

**Issue by drawcard** [pdaddyo/soundbounce#148]
Hi,

Just a general comment that I notice a bit of lag from time to time when scrolling through a song list or interacting with the interface in general. Mac OSX 10.10.1 - Macbook Air 2013

**Comment by pdaddyo** [comment]
Yes, apparently the new UI with blurred background is slightly laggier.  User settings are coming - #100, and will include a "performance" theme which will look more basic but be smoother. Thanks!
