### ISSUE TITLE
"Add new tracks to this room" list suggests adding Coldplay songs to room playlist.

### ISSUE THREAD

**Issue by bgod** [pdaddyo/soundbounce#151]
;-)  It's a nice feature, but where does the list source from?  Can we blame the Spotify API?  Do we expect the suggestions to get better over time?  Perhaps this list should instead pull from the room's top up playlist?

**Comment by pdaddyo** [comment]
It comes direct from spotify's api, it doesn't even go to our server to do this (your client connects directly to the Spotify Web API) - would rather keep it this way.

This does however mean you can use their elasticsearch features like:

fix you NOT artist:coldplay  

Which gets you songs called "fix you" by other artists - https://db.tt/cHvKO4hW

Cool eh!

**Comment by bgod** [comment]
Nevermind, I think the UI is just kind of sticky and I was confused about what I was looking at.  I think I must have typed an "a" in the Search field and deleted it.  The Search field was empty but the "Add" section was still there below the playlist with results suggesting all sorts of unrelated bands (Coldplay, Tiesto, The Fray).  I mistakenly assumed it was a new feature soliciting adds by suggesting songs for the room.  And I was kind of scratching my head about where the suggestions came from.  

But I'm glad I asked because the elastic search thing is very cool!
