### ISSUE TITLE
Unable to add tracks that do not have album photos on Spotify while using Mac OS X Yosemite 10.10

### ISSUE THREAD

**Issue by Loungeness** [pdaddyo/soundbounce#156]
Cannot add tracks that don't have album photos to Soundbounce from Spotify on Mac OS X Yosemite 10.10, Not sure if its just a Mac specific issue. But the workaround is to find the same track on a different album that has a picture.

**Comment by pdaddyo** [comment]
Thanks for your feedback, please can you give an example of a track like this?

**Comment by Loungeness** [comment]
For Example: http://open.spotify.com/track/5s6qgp5vWymlPntlYxXF2Q

**Comment by pdaddyo** [comment]
This affects all platforms, fix coming now....
