### ISSUE TITLE
Removing Auto Top-up Playlist will remove all tracks

### ISSUE THREAD

**Issue by JohnnyCrazy** [pdaddyo/soundbounce#157]
When you remove your Top-Up Playlist, it will remove all the tracks in your room.
I don't think this is a good idea. I e.g used it to import my tracks.

**Comment by Allikin** [comment]
Agreed, but in the future you can do the same by just marking all the tracks in your playlist and drag them into Soundbounce.

**Comment by pdaddyo** [comment]
Shouldn't remove them all immediately, just they won't re-appear if they were added automatically as opposed to manually.
