### ISSUE TITLE
Regarding favourite/recently visited rooms #11 and #12

### ISSUE THREAD

**Issue by noafro1991** [pdaddyo/soundbounce#160]
I think the best option would be a drop down menu on the same level as the search bar, but on the left hand side. It'll use up that gap.

Only thing I am not sure of with this though is if the SB window is set to it's minimum distance where there is a single column of room links. The drop down menu would have to go underneath the search bar then maybe.

Thoughts?

**Comment by pdaddyo** [comment]
We have a plan here for a persistent top bar, with room list top left.  Closing for now since this is mentioned in other issues.  Cheers Daniel!
