### ISSUE TITLE
Keeping Playlist Fresh

### ISSUE THREAD

**Issue by SKGibb** [pdaddyo/soundbounce#161]
Trying to get my head around how it works - are there developments in the pipe, for example: Refresh entire room? 

I have linked the IFR room to a master playlist of over 5000 tracks, and each day listeners pop in and add great new tracks. However, after a nights sleep I return and the room looks painfully similar to how it was the day before. Some tracks seem to survive for way to long, while others are not recycled. 
Any help?

**Comment by pdaddyo** [comment]
Tracks that have been added manually (not from auto-top up) will cycle around, this will be addressed so they'll only do 2 loops around if they get no votes.  See #96 - closing this as a duplicate of that issue.  Thanks!
