### ISSUE TITLE
Cannot open room

### ISSUE THREAD

**Issue by astrowaffle** [pdaddyo/soundbounce#162]
I'm logged in via facebook credentials and I have a spotify premium account.  I get to the page where the rooms are listed but when I click on one it just says "joining..." and then nothing happens.  I'm on windows 7.

**Comment by bgod** [comment]
Was it working for you earlier or has it never worked?  That happened to me recently.  It seemed like I had an abandoned session.  I'm not sure how I worked around it, but I think I closed Soundbounce, logged in and out of the Spotify desktop client, and then back into Soundbounce.  Something like that.  If you've never successfully joined a room though, then maybe you are seeing something different.

**Comment by bgod** [comment]
If it has never worked, test websockets:  http://websocketstest.com/

**Comment by pdaddyo** [comment]
Closing because this is a websockets issue. May be addressed with #153 but that's long term.
