### ISSUE TITLE
Request for marking rooms as "Official"

### ISSUE THREAD

**Issue by saber667** [pdaddyo/soundbounce#164]
It would be useful to be able to mark rooms as "Official" within the data set and give priority to these rooms when returning search results.  For example, there are two Electro House rooms:
Electro House
Electro house

By establishing "official" rooms, it would be easier to gather groups of people interested in a specific genre within a single room.

**Comment by JohnnyCrazy** [comment]
Yes, we already talked about this. :+1: 

And also, with having official rooms sometimes in the future, we then need the implementation behind #141.

**Comment by saber667** [comment]
Great!  I just didn't find it when searching the list of open issues, so I thought I'd add it.  FYI - I'd be happy be the admin for the "official" Electro House room, with the preferred capitalization:  "Electro House".

**Comment by JohnnyCrazy** [comment]
Maybe we could mark rooms with a little label attached on left/right side?

small mockup(just some thoughts):
![image](http://i.imgur.com/Kktaatu.png)

**Comment by FloorvanLamoen** [comment]
Who decides about being "official"?

**Comment by JohnnyCrazy** [comment]
Probably @pdaddyo with some assistance by the users?

**Comment by Allikin** [comment]
And who would run the official rooms? Who would decide who to run them? This isn't Soundrop with a group of owners, it's not quite the same.

I do think there should be a restriction on naming romos though. As in each room should have a unique name.

**Comment by pdaddyo** [comment]
Hmmm not sure about this - would be a bit autocratic if I can choose what is and isn't "official".  If we want it as a democracy, it's kind of already like that - top rooms go to the top of the list.

Room names being unique - definitely! I thought this check was in place....

**Comment by pdaddyo** [comment]
Apparently it's a case thing e.g. Electro House vs Electro house - my bad.  Will fix!

**Comment by pdaddyo** [comment]
Closing this, will fix issue discussed above in #165.

**Comment by JohnnyCrazy** [comment]
Uhm...so no real discussion about official rooms?

Without it, it will just result in a lot of rooms with the same tracks/genre with 1-2 listeners

**Comment by pdaddyo** [comment]
I think if we prevent super-similar room names, people will hopefully congregate naturally.  Else I'll have to make disputable decisions about what's considered "official" - so I'm not a huge fan of the idea.  If you spot combinations of rooms that should be "merged" (like Electro house and Electro House), list them in this thread and I'll remove one of them.  Cheers.

**Comment by saber667** [comment]
I addition to removing case-sensitivity when checking for duplicates, what about removing whitespace? For example:
Cali -Roots 
Cali-Roots

I'm guessing one of these rooms was created, then abandoned due to the extra space in the name, and the creator didn't take the time to delete the abandoned room.

**Comment by pdaddyo** [comment]
Yeah good call.  I'll remove these unused rooms soon too.
