### ISSUE TITLE
Home screen room list needs to be paged

### ISSUE THREAD

**Issue by pdaddyo** [pdaddyo/soundbounce#170]
Side effect is searching for rooms will need to query the server, unless when you click on the search box it grabs all the rooms, maybe?

**Comment by FloorvanLamoen** [comment]
Perhaps put rooms into theme folders?

**Comment by JohnnyCrazy** [comment]
Whats your definition of Themes? Like some kind of genre?

**Comment by FloorvanLamoen** [comment]
My wild suggestions usually come without definitions. But one could think of "genre rooms", "mood rooms", "user group rooms", not far away from what Soundrop used. Folders per genre doesn't seem to be very useful now.
