### ISSUE TITLE
Pause music in room

### ISSUE THREAD

**Issue by jbuda** [pdaddyo/soundbounce#174]
If a room only has one listener (you), would be useful to be able to pause the playlist with the button pause button in the top left.

If the room has more than one person, then the current function would be the same as it is now. 

If another user enters the room whilst it is in a Pause state, then the music just resumes as usual.

**Comment by pdaddyo** [comment]
Thanks for feedback, but I don't think we'll do this - doesn't really suit the style of Soundbounce I don't think, a lot of work for a feature that could be confusing. For example, when browsing rooms, you go back and it's still on same track 20 minutes later due to an "auto pause"
