### ISSUE TITLE
Suggested Feature - History via RSS or simply channel play history (maybe the last 5, 10, or 25 songs?)

### ISSUE THREAD

**Issue by inzi** [pdaddyo/soundbounce#175]
Heard a song someone added and it was great - but I was tied up and couldn't get to my computer to star it. Once it finished, there's no way to find out what played.

In SoundDrop - the last song played would automatically drop to the bottom of the queue. 

With SoundBounce, there is no such way to find it.

**Comment by pdaddyo** [comment]
Good idea, dupe of #147
