### ISSUE TITLE
Add server command /listadmins

### ISSUE THREAD

**Issue by pdaddyo** [pdaddyo/soundbounce#178]

**Comment by pdaddyo** [comment]
Should non-admins be allowed to see this list?  I think they should... thoughts?

**Comment by Tonybyte** [comment]
doesnt seem like a problem imo either.  currently, the main reasons to remain anonymous don't seem to apply on SB.

**Comment by FloorvanLamoen** [comment]
Agree with it being allowed.

**Comment by pdaddyo** [comment]
This is now live - /listadmins

**Comment by bgod** [comment]
Thanks for all the recent updates! :clap: :+1:
