### ISSUE TITLE
Add chat command /me <action>

### ISSUE THREAD

**Issue by carnager** [pdaddyo/soundbounce#184]
yes, tiny feature, but still i think this makes chatting a whole lot better.

**Comment by Tonybyte** [comment]
not sure if u are aware of the new  /commands for admins. Paul took it from idea to implemented in what felt like less than an hour.  

specific suggestions are probably welcomed for something like /me
/listadmins works for everyone

There are a lot of possibilities with it. :)

**Comment by pdaddyo** [comment]
yeah /me should be added I think. I'll rename this issue.

**Comment by noafro1991** [comment]
I usually see /me text come out as italic in other conversations to indicate that it was that action. Another small action that could be useful if needed.

**Comment by andrewthecoder** [comment]
Implemented and deployed on live - give it a try!
