### ISSUE TITLE
For fun! Make Soundbounce act like a robot :)

### ISSUE THREAD

**Issue by noafro1991** [pdaddyo/soundbounce#185]
So when a user says "hey" or something Soundbounce will say hi back in chat!

Thought I'd add a fun suggestion! :smile: 

"Shut up Soundbounce!" "Make me!"

hehehehe

**Comment by pdaddyo** [comment]
Similar to the Slackbot on slack... if we can think of a useful idea for it I'll consider it :smile:

**Comment by Allikin** [comment]
I thiink it is usefult for for having the room  talk to listeners maybe? Like on Soundrop?

"Please add Dubstep only!"

Love, 
your average nazi
