### ISSUE TITLE
Official IRC channel?

### ISSUE THREAD

**Issue by carnager** [pdaddyo/soundbounce#189]
Could you imagine creating an official channel on freenode?
Every open source project needs one! :)

Joking, but it's worth a shot, I guess.

**Comment by pdaddyo** [comment]
Happy to have a channel - there tends to be a lot of dev talk in whichever room i'm listening in so a good plan I think.  Let's do this!

**Comment by pdaddyo** [comment]
I created #soundbounce on freenode, I haven't used IRC in years - will channel disappear if I leave it now?  Can someone leave a bot in there maybe?  Thanks!

**Comment by pdaddyo** [comment]
[20:58] -ChanServ- #soundbounce is now registered to pdaddyo.

I think I own the channel now!

**Comment by carnager** [comment]
yup, chanserv is the way to go
