### ISSUE TITLE
Starring

### ISSUE THREAD

**Issue by FloorvanLamoen** [pdaddyo/soundbounce#219]
Starring doesn't seem to add a track to your favourites in Spotify anymore.

**Comment by pdaddyo** [comment]
Just checked and it's working here on Windows + OSX, should be appearing in your Starred playlist.  Libspotify doesn't let us add to "Your music"  unfortunately.

One thing, if the track was already starred, it will not jump to the top of the list.

**Comment by pdaddyo** [comment]
Checked this again, seems to be working so closing this.  Perhaps song was already starred?

**Comment by FloorvanLamoen** [comment]
The issue seems to be solved indeed. After your first reply I still didn't succeed in starring...
