### ISSUE TITLE
Android App

### ISSUE THREAD

**Issue by AstyzTheWise** [pdaddyo/soundbounce#222]
I am trying to log into the app on my Galaxy S5 on the google play store.   I input my spotify email and then it asks if i want to use twitter or facebook.  I choose facebook and i get this weird screen that almost seems like it wants me to log into facebook, but i cant.  I then click on the onscreen "soundbounce" link and it fails.

**Comment by andrewthecoder** [comment]
Hi Astyz,

Sorry to hear that. The Android app is still only an alpha version and really only works well on large screens (tablets, TVs etc) right now.

However, the issue you're describing is a weird one - any chance you could provide screenshots?

Just a long shot, but have you ever successfully logged into soundbounce using the desktop client on a computer before? If not, you (at the moment, until I fix it) have to log in at least once there before trying to log in on Android.

Cheers,
Andrew

**Comment by AstyzTheWise** [comment]
Hey Andrew,

I instead logged onto the app with my twitter with no complications.  I
tried to log out and retry with my facebook as to provide a screenshot, but
I couldnt quite figure out how.  Either way it works perfectly now.

Thank you,
Alex
