### ISSUE TITLE
Re-enable add room admin command

### ISSUE THREAD

**Issue by TimVervers** [pdaddyo/soundbounce#227]
The title says it all. Can there be a function implemented that support deleting songs from a room?

**Comment by pdaddyo** [comment]
You can delete songs from a room if you are an administrator.  To find out who is an admin in your room, type "/listadmins" into the chat window.  Also, all users can remove their own adds to a room too (a trash icon appears on the track for the adder / admin).  Top tip: you can hold ctrl whilst clicking remove track to bypass the confirmation dialog, to delete a few in a row.  Also room admins can use /clearall to start afresh.

**Comment by TimVervers** [comment]
Dear pdaddyo,

I just checked the administration list using /listadmins and it confirmed that i was indeed an Administrator. Sadly I am still unable to remove tracks that other users added in my room (strangers). As you can see in this screenshot i can't delete the added song : http://gyazo.com/77a780600de291116a07f300df607657

Thanks in advance,

Tim

**Comment by TimVervers** [comment]
I found the issue.. I was logged in using facebook instead of my actual Spotify ID. It seems that these 2 users aren't equal to eachother so i wasn't an administrator anymore.

Is there a way to assign an admin? I also would like to give my friend permission to delete songs.

Thanks in advance!

Tim

**Comment by pdaddyo** [comment]
I've currently disabled the ability to add further admins to a room but should be re-enabling in the coming weeks.

**Comment by pdaddyo** [comment]
OK this is back, thanks.
