### ISSUE TITLE
Creating an own Keys.cs after clone

### ISSUE THREAD

**Issue by TimVervers** [pdaddyo/soundbounce#228]
I just downloaded the entire Soundbounce project and opened it in my Visual Studio. Currently it's not building because i'm missing the file keys.cs (obviously cause i'm using diffrent spotify API keys). I was wondering if you could post the Keys.cs without the actual keys inside (a part that a user can replace to make the project build in VS).

Thanks

Tim

**Comment by pdaddyo** [comment]
Sure thing Tim, I created a gist for you here: 

https://gist.github.com/pdaddyo/3076f28fcb7664c12396

I also created a template for the config.js, needed on the node server.

https://gist.github.com/pdaddyo/69c22b7044565828d7b8

Thanks

Paul
