### ISSUE TITLE
Windows app launches blank screen

### ISSUE THREAD

**Issue by RossBlakeD** [pdaddyo/soundbounce#229]
I reinstalled and rebooted.
When I launch Soundbounce from Windows 7, I just get a blank screen. Started about 12pm Pacific today. It was ok earlier.

![soundbounce](https://cloud.githubusercontent.com/assets/7061931/7221889/f6de5126-e6b3-11e4-90f8-c3212561fbdd.JPG)

**Comment by pdaddyo** [comment]
This was a server issue, and is now resolved. Thanks!

**Comment by crbarahona** [comment]
Looks like the issue is back, though. Server down again?

**Comment by TimVervers** [comment]
Server issue again? It seems to be the same problem
