### ISSUE TITLE
[Feature Request] Vote to skip & vote to skip/kick.

### ISSUE THREAD

**Issue by inzi** [pdaddyo/soundbounce#230]
SoundDrop had a vote to skip feature - I propose implementing something similar. 

In Sound Drop - it took 5 votes to skip. I propose Sound Bounce do the same, but if there are less than 5 people in a room, then go with greater than 50% votes skips.

I was thinking move that two votes to skip would remove from queue, but to make it easier it might be better to also have a vote to kick - and that would require 100% channel vote (if less than 5) or 5 votes. Such an action would skip and remove the song from the playlist.

I'm not a contributor - but if I can find a way to implement I'll fork and try.

**Comment by andrewthecoder** [comment]
Implemented and deployed on live - give it a try! The skip button is next to the other buttons on the right of the now playing track.

**Comment by TimVervers** [comment]
It's a cool feature andrew. One question, is it meant to delete the song from the playlist if you "Vote to skip"? I presumed it would go back into the queue (maybe at the last spot) and not actually delete the song from the room. Else it might be better to rename the button to "Vote to kick track"

**Comment by pdaddyo** [comment]
Andrew - I created this bug whilst trying to fix the null track issue during go-live.  We need to send track back to bottom of room, with votes stripped.  Preferably via the handleRemoveTrack function so it only cycles under 200 tracks.
