### ISSUE TITLE
[Feature Request] Persist information on who added a track

### ISSUE THREAD

**Issue by mreinhardt** [pdaddyo/soundbounce#231]
Currently you can see who added a track when it is first added. However once it's played and cycled to the end of the queue that is no longer visible.

It would be nice if that persisted so that when that track is played again users can tell who added it even if they weren't in the room when it was added.

Credit where credit is due, props, street cred, and all that.

**Comment by pdaddyo** [comment]
Definitely intend to add this.  Related to #72

**Comment by pdaddyo** [comment]
We now have an "extra details" view (click on the title of a track in the queue) - would be the perfect place for this.  Definitely still planning to add....

**Comment by pdaddyo** [comment]
This is now live!  needs to show when added though, will open an issue for that.
