### ISSUE TITLE
Cannot join rooms on Windows

### ISSUE THREAD

**Issue by mikeymurph77** [pdaddyo/soundbounce#238]
I'm having issues trying to join rooms. If I click on a room, it says "Joining" but then nothing happens. Also when I create a room, I cannot join it. I am running Windows 8.

**Comment by CoMiGa** [comment]
I had the same problem. On the log in screen click "having trouble
connecting to rooms" and try a different port. 443 worked for me.

**Comment by mikeymurph77** [comment]
:+1: Thanks works now
