### ISSUE TITLE
Entire list of songs got removed from room

### ISSUE THREAD

**Issue by TimVervers** [pdaddyo/soundbounce#241]
I created a room around 3 months ago and added around 150 songs to it. Suddently after the server crash everything is gone now. The room still exists but is empty. This also occured with another room i created 3 weeks ago.

The rooms are called "Angry White Boys" and "Angry Black Boys".

Is there a way to recover this?

Tim

**Comment by FloorvanLamoen** [comment]
This may be related: it seems that auto top up doesn't function properly. The Planet Jazz Room has an underlying Spotify playlist, but only has 48 tracks listed at the moment.

**Comment by TimVervers** [comment]
Could be, after using /topup i was able to re-add the songs from the playlist i linked it with. But i also only added 50 songs instead of 120. I spammed the /topup command and that brought the song list back up to the original 102 songs. I'm still missing the songs i added manually to the room tho.

**Comment by pdaddyo** [comment]
Yes this is our server hitting the rate limit of the spotify API,  so some topup requests fail.  Try again a moment later and it should be fine.  I'm looking into handling this better on the server.

**Comment by TimVervers** [comment]
Mmm.. This was never a issue tho, weird. Does that also explain why songs that i add manually get removed after being played? Apperently the room was empty because it just kept on playing (like it should) but deleted the song from the room after it is done.

**Comment by FloorvanLamoen** [comment]
@pdaddyo auto-topup doesn't seem to function at all. Manual topup does function.

**Comment by pdaddyo** [comment]
Ah ok, interesting.  I'll take a look at the auto-top up when I get a chance, maybe we've been rate-limited even harder now since I haven't changed anything on the server.....
