### ISSUE TITLE
Cannot find libspotify.

### ISSUE THREAD

**Issue by Benn120** [pdaddyo/soundbounce#242]
Just finished downloading and installing and I'm getting the following message on the login screen:

Oops - cannot find libspotify. Please double-check the installation instructions... etc.

I currently have premium Spotify, however this may be stemming from my Spotify being installed on a drive other than C:\ (which is a 100GB SSD, so I'd rather not fill it with music :\ ). Is there something I'm overlooking or some fix for this?

**Comment by pdaddyo** [comment]
Hi Ben,  Are you on windows?  Seen this error on OSX before but not windows...

**Comment by abatewongc** [comment]
I'm getting this as well. Windows 8.1, premium Spotify.

**Comment by pdaddyo** [comment]
@abatewongc Can you try running this as administrator please - thanks!

**Comment by abatewongc** [comment]
Works. huh. Welp
