### ISSUE TITLE
Songs being deleted from playlist

### ISSUE THREAD

**Issue by kevlarkoala** [pdaddyo/soundbounce#243]
I have a room on Soundbounce that had around 300 songs in it, and then it started deleting songs. It dropped down to 150 randomly, so I started adding them back. After an hour or two, the room slowly started removing songs, and I didn't notice until it deleted the song that was currently playing. Room name is "Boats & Hoes Vol 7"

**Comment by pdaddyo** [comment]
We've been hitting the "rate limit" of the spotify API on the server, so sometimes songs do not cycle correctly within rooms.  We're looking into fixes for this, thanks for your patience.

**Comment by TimVervers** [comment]
This is related to #241
