### ISSUE TITLE
Chrome Extension does not seem to support admin commands

### ISSUE THREAD

**Issue by RossBlakeD** [pdaddyo/soundbounce#273]
I am not the room creator but I was made an admin in a room by the creator. 
As such, I can shuffle the list and a few other commands. 
The extension does not allow me to shuffle and responds with an error:
"Nice try, you must be a room admin to use the command /shuffle"

**Comment by pdaddyo** [comment]
You are probably using a slightly different spotify login in the chrome extension (under the hood), so SB sees you as a non-admin.

If you let me know which room you're supposed to be an admin in I can re-add you.

**Comment by TimVervers** [comment]
I had this issue before. I logged in with my Facebook account and once i logged in with my actual Spotify account. Apparently these accounts are equal but SB sees it as 2 separate accounts.

**Comment by pdaddyo** [comment]
Yes exactly right - I thought "spotify username" would be unique to each spotify user, but it's not.
