### ISSUE TITLE
chrome extension does not work

### ISSUE THREAD

**Issue by carnager** [pdaddyo/soundbounce#275]
Using it on Arch linux 64bit, chromium version 43. 
The search field does exactly nothing, doesn't even accept input.
trying to change the url manually gives a pop up with "internal error"

Also it says "0 listeners online"

**Comment by ikt** [comment]
I also had the same issue, it now works ok though.

**Comment by carnager** [comment]
just tried again. issue remains

**Comment by pdaddyo** [comment]
This is now fixed, was a bug with a room being deleted that took down the server for an hour.
