### ISSUE TITLE
I made an oopsie

### ISSUE THREAD

**Issue by TimVervers** [pdaddyo/soundbounce#277]
I think i broke soundbounce... I deleted a room but for some reason it just crashed. Apperently my friends also can't log in anymore.

![](http://i.gyazo.com/88c724fd96b62018c1ab3da035a4f0d0.png)

Is this just us or should i apologize?

**Comment by TimVervers** [comment]
App also broke... :( 

![](http://i.gyazo.com/1807840aeacb971f142b42a84e13240e.png)

**Comment by TimVervers** [comment]
Error gettings room list

![](http://i.gyazo.com/e80bd65e357309c4f7b9df03f4996410.png)

**Comment by pdaddyo** [comment]
Sorry missed this message on github (off on paternity leave!), but I did fix the issue at the time.

Thanks
