### ISSUE TITLE
Making the SpotifyAPI a nuget package

### ISSUE THREAD

**Issue by fiLLLip** [pdaddyo/soundbounce#280]
Hi, I've been fiddling with my own private project now to make a Spotify client which plays music based on votes (one system playing, voting online). I have extracted the SpotifyAPI available in this repo to use in my project, but because of that, my commits will include your code.
It would be great to see the SpotifyAPI in itself available as a nuget package to use instead of commiting your code into my repo. Any thoughts ?

**Comment by pdaddyo** [comment]
Hey!  I've never created a nuget package but more than happy for that to become one.  The request to allow voting without listening has come up a few times - would be great for office / shared environments.  If you did want to implement it as a feature of soundbounce I'd happily accept your PR. Equally, good luck developing your own project, and if you want to chuck that code on nuget (using MIT license) that's fine by me too!  Cheers,  Paul

**Comment by fiLLLip** [comment]
You can check out my project over here: https://github.com/ZarGate/spotify-client
We are using it at a LAN Party where participants vote at our web page. The client is "dumb" and just requests the next song to play :)
I tried to credit you guys in the README over there.

**Comment by pdaddyo** [comment]
Cool, glad it was of use to you!
