### ISSUE TITLE
How install on OSX El Capitan

### ISSUE THREAD

**Issue by jchesne** [pdaddyo/soundbounce#289]
I can not find the folder ~/Library/Frameworks/

**Comment by jchesne** [comment]
OK, just create the missing Framework folder in my case.

**Comment by rjhilgefort** [comment]
@jchesne I believe the documentation shoot be directing people to locate the `Frameworks` folder at root:

`/Library/Frameworks/` rather than `~/Library/Frameworks/`

But, if it worked for you to put in the latter, it's probably because OSX looks in both places.
