### ISSUE TITLE
Could librespot substitute libspotify?

### ISSUE THREAD

**Issue by cfq20** [pdaddyo/soundbounce#296]
I was wondering if you had already considered using the librespot library developed by @plietar here:
[https://github.com/plietar/librespot](url)

Could this be used as a substitute for the proprietary libspotify library that soundbounce uses currently?

I should say I knew neither your project not the one I just mentioned above until a couple of minutes ago, so I just wanted to make you aware of the existence of the other project, in case that could extend the use of the soundbounce client to non-Premium Spotify users?

**Comment by pdaddyo** [comment]
Thanks, we're taking a 100% web-based approach with v2, see https://github.com/pdaddyo/soundbounce-v2/ or https://v2.soundbounce.org/ for our prototype using Spotify Connect!
