### ISSUE TITLE
Starring a track should show something in the chat

### ISSUE THREAD

**Issue by andrewthecoder** [pdaddyo/soundbounce#49]
Just like voting or adding tracks ^^

**Comment by noafro1991** [comment]
I was just thinking about this. Guess it's obviously sought after! Simple example would be

.Self message
:star:  Starred All My Dogs (Platinum Monkey Remix) by Glitter

Other user message
:star:  Daniel Scott starred All My Dogs (Platinum Monkey Remix) by Glitter
