### ISSUE TITLE
boss / panic button

### ISSUE THREAD

**Issue by Tonybyte** [pdaddyo/soundbounce#65]
Also not high priority and I'm sure there is an app out there somewhere but hey, if it's easy... Make a customization shortcut key to minimize Soundbounce even if it's not the active window. A great office feature.

**Comment by pdaddyo** [comment]
We're not gonna add this, suggest using AutoHotKey to automate minimising on Windows, or use an "office" friendly theme.  Cheers.

**Comment by zackram** [comment]
Minimal theme provided by Anita Berge is working awesome for me. Link: (check out the last two) : https://dl.dropboxusercontent.com/u/98755356/Soundbounce_Themes/themes.html# 

if u need any implementing the theme, let us know. :)

**Comment by zackram** [comment]
ill just put this in for anyone who needs it. 


IMPLEMENTING A THEME: 

my computer was locked down for admin stuff @ work so I: 

(on Windows)
uninstalled SB (skip if u r an admin)
reinstalled SB in the "Documents" folder (skip if u r an admin)
pick your theme from the link above and click on it
copy all the code
Go to Documents, Soundbounce folder, Themes, Open "Default" in Notepad
Remove any code (if there is any there) and paste the code you copied.
save the file
restart SB

works like a charm. :)

loving the dark minimal theme.
