### ISSUE TITLE
Notify of joiners / leavers in room

### ISSUE THREAD

**Issue by pdaddyo** [pdaddyo/soundbounce#7]

**Comment by noafro1991** [comment]
Might not be needed in my opinion. Depends what you have in mind?

**Comment by pdaddyo** [comment]
Defo not a priority... might not do it at all...

**Comment by pdaddyo** [comment]
Decided not to do this since we can see the connected list easily enough.  Some UI upgrades coming in that department anyway, so closing this as wontfix.
