### ISSUE TITLE
allow admin to add without voting

### ISSUE THREAD

**Issue by Tonybyte** [pdaddyo/soundbounce#74]
As a list curator, I like to add top releases at least weekly. Sometimes it may be 50 or 100 tracks I want in rotation but don't want to block or force other voters. i just want them in rotation.

As a work-around in Soundrop, I would often add late at night with less people in the room and then shuffle when there weren't any votes. This would remove my votes for the 50 tracks.

A solution example might be for an admin to hold ctrl or shift when dragging and dropping to add without voting.

**Comment by pdaddyo** [comment]
Admins can essentially do this now using new commands, using /topup spotify:playlist:uri - that will add 50 random tracks from that playlist without voting.  Also admin can add all the tracks by drag drop, then /shuffle to remove votes.
