### ISSUE TITLE
Suggestion: Load some type of default cover art when track's real art fails to load.

### ISSUE THREAD

**Issue by bgod** [pdaddyo/soundbounce#99]
![no-art](https://cloud.githubusercontent.com/assets/10253473/5532229/88336f62-8a02-11e4-876e-fb5a15522563.jpg)

**Comment by pdaddyo** [comment]
This is now fixed properly - some tunes do not have artwork e.g. http://open.spotify.com/track/5s6qgp5vWymlPntlYxXF2Q - this now loads a blank icon instead.
